name: Build Flutter APK From Drive
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download File From Drive
        run: |
          curl -L -o app_code.zip "https://docs.google.com/uc?export=download&id=1cH9ocnr2kzv3ND4GSbZ6xSVym4sO2oVn"
          unzip app_code.zip -d flutter_project
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build APK
        run: |
          cd flutter_project
          flutter pub get
          flutter build apk --release
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: flutter_project/build/app/outputs/flutter-apk/app-release.apk
          
